#!/usr/bin/env python3
"""Build a level disk: the construction kit plus 128 blank level files.

The game only ever loads LEVEL nnn once it is running, so this disk can be
swapped in at the press-fire prompt and the game will take its levels from
here.  The kit is first in the directory, so LOAD"*",8 finds it.

The levels are an original set generated by genlevels.py: none of the
shipped Deeper Dungeons layouts are reproduced here.
"""
import argparse, glob, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
_ap = argparse.ArgumentParser(description=__doc__)
_ap.add_argument('--levels', default=os.path.join(HERE, 'levels'),
                 help='directory holding LEVEL_001.prg .. LEVEL_128.prg')
_ap.add_argument('--kit', default=os.path.join(HERE, 'gauntkit.prg'),
                 help='the construction kit .prg to put first on the disk')
_ap.add_argument('--out', default=os.path.join(HERE, 'gauntlet_levels.d64'),
                 help='the .d64 to write')
_args = _ap.parse_args()
OUT = _args.out
KIT = _args.kit
LEVELDIR = _args.levels
DISKNAME = b'GAUNTLET LEVELS'
KITNAME = b'GAUNTLET CO. KIT'      # 16 characters, the CBM maximum
DISKID = b'GK'


def spt(t):
    return 21 if t < 18 else 19 if t < 25 else 18 if t < 31 else 17


def off(t, s):
    base = 0
    for tr in range(1, t):
        base += spt(tr) * 256
    return base + s * 256


d = bytearray(683 * 256)

# ---- BAM: every sector free, then take 18/0 and 18/1
bam = off(18, 0)
d[bam], d[bam + 1] = 18, 1                      # first directory sector
d[bam + 2] = 0x41                               # DOS version 'A'
for t in range(1, 36):
    o = bam + 4 * t
    n = spt(t)
    d[o] = n
    bits = (1 << n) - 1
    d[o + 1] = bits & 0xFF
    d[o + 2] = (bits >> 8) & 0xFF
    d[o + 3] = (bits >> 16) & 0xFF
d[bam + 0x90:bam + 0xA0] = DISKNAME.ljust(16, b'\xa0')
d[bam + 0xA0:bam + 0xA2] = b'\xa0\xa0'
d[bam + 0xA2:bam + 0xA4] = DISKID
d[bam + 0xA4] = 0xA0
d[bam + 0xA5:bam + 0xA7] = b'2A'
d[bam + 0xA7:bam + 0xAB] = b'\xa0' * 4


def take(t, s):
    o = bam + 4 * t
    if not d[o + 1 + s // 8] & (1 << (s % 8)):
        sys.exit('sector %d,%d already used' % (t, s))
    d[o] -= 1
    d[o + 1 + s // 8] &= ~(1 << (s % 8)) & 0xFF


def free(t, s):
    o = bam + 4 * t
    return bool(d[o + 1 + s // 8] & (1 << (s % 8)))


take(18, 0)
take(18, 1)
o = off(18, 1)
d[o], d[o + 1] = 0, 0xFF                        # last directory sector, for now

nxt = [1, 0]                                    # next free sector to try


def alloc():
    t, s = nxt
    while True:
        if t != 18 and free(t, s):
            take(t, s)
            nxt[0], nxt[1] = t, (s + 10) % spt(t)
            return t, s
        s += 1
        if s >= spt(t):
            s = 0
            t += 1
            if t > 35:
                sys.exit('disk full')


dirsecs = [(18, 1)]
entries = 0


def add_entry(name, first, blocks):
    global entries
    slot = entries % 8
    if slot == 0 and entries:
        # chain another directory sector
        t, s = 18, 2
        while not free(t, s):
            s += 1
            if s >= spt(18):
                sys.exit('directory full')
        take(t, s)
        po = off(*dirsecs[-1])
        d[po], d[po + 1] = t, s
        no = off(t, s)
        d[no], d[no + 1] = 0, 0xFF
        dirsecs.append((t, s))
    o = off(*dirsecs[-1]) + 2 + slot * 32
    d[o] = 0x82
    d[o + 1], d[o + 2] = first
    d[o + 3:o + 19] = name.ljust(16, b'\xa0')
    d[o + 28] = blocks & 0xFF
    d[o + 29] = blocks >> 8
    entries += 1


def write_file(name, data):
    need = (len(data) + 253) // 254
    chain = [alloc() for _ in range(need)]
    for i, (t, s) in enumerate(chain):
        o = off(t, s)
        part = data[i * 254:(i + 1) * 254]
        if i + 1 < need:
            d[o], d[o + 1] = chain[i + 1]
        else:
            d[o], d[o + 1] = 0, len(part) + 1
        d[o + 2:o + 2 + len(part)] = part
    add_entry(name, chain[0], need)
    return need


assert len(KITNAME) <= 16, 'a CBM filename is 16 characters at most'
total = write_file(KITNAME, open(KIT, 'rb').read())

# an original 128-level set, generated by genlevels.py; nothing here comes
# from the shipped levels
for n in range(1, 129):
    data = open(os.path.join(LEVELDIR, 'LEVEL_%03d.prg' % n), 'rb').read()
    total += write_file(('LEVEL %03d' % n).encode(), data)

open(OUT, 'wb').write(bytes(d))
used = sum(d[bam + 4 * t] for t in range(1, 36) if t != 18)
print('%s: %d files, %d blocks used, %d free'
      % (os.path.basename(OUT), entries, total, used))
